### ISSUE TITLE
question regarding adding transpose

### ISSUE THREAD

**Issue by tensorbuffer** [paulbauriegel/tensorflow-tools#4]
Hi,
From the code transpose() is added for input, but not filter, I wonder why? Don't you need to transpose both? If the model is trained with NCHW, then the filter values are stored in NCHW. Maybe you re-arranged weights offline? If so do you have scripts for that?

**Comment by tensorbuffer** [comment]
Ok I think this code is after the onnx-tf, which already added transpose for the filters. Is this correct?
I wonder taking a NCHW model, can I change it to NHWC without adding transpose? Assuming the input is already preprocessed to be NHWC. I can just modify the weights to rearrange them to NHWC, and change the operator attributes accordingly (like what you do here with the stride, etc.).

**Comment by paulbauriegel** [comment]
Excuse the late reply. I'm not sure I get your question right, because what I did was adding transpose nodes before and after the convolution operations. I didn't touch the original weight of the convolutions, even though that would have been a cleaner approach that wouldn't impact the performance that heavily. So all I did was adding these transpose nodes and removing the nchw flag from the convolutional operations so that the model would behave like a NHWC even though it wasn't really. Does that help you?

**Comment by tensorbuffer** [comment]
My first post is specifically to your code. My second post is a generic question.
Let's talk about my first post, e.g. why your code only add transpose to the conv input (L17) but not the filter (L23)? My understanding is that your code is supposed to be used AFTER the onnx-tf project, which already added transpose to the filters, right?

**Comment by paulbauriegel** [comment]
@tensorbuffer Yes most models came from pytorch and then I used onnx-tf. As far as I know in Tensorflow the NCHW format is only used for the input data, but not for the filters. That's probably why the attribute is called data_format. I haven't checked if onnx-tf is transposing anything or not. I only checked for the models if the output is the same. However as I understand the TF documentation for the [conv2d](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d) for instance the filters attibute should always have the same shape, independently in which weights data format your're working.
